import Container from "@/components/layouts/Container";
import Head from "next/head";

export default function Nft({}) {
  return (
    <>
      <Head>
        <title>Radish Square: The Friendliest Platform in the World!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container></Container>
    </>
  );
}
