import Head from "next/head";
import Image from "next/image";
import { Button } from "antd";
import { MdGroupAdd, MdOutlineShare } from "react-icons/md";
import { ReactComponent as TwitterIcon } from "../../images/profile/tw.svg";
import telegramLogo from "../../images/profile/telegram-logo.png";
import banner from "../../images/collection-banner.png";
import ProfileMain from "@/components/profile/ProfileMain";
import Container from "@/components/layouts/Container";
import WalletNumber from "@/components/utils/WalletNumber";
import axios from "axios";

export default function Profile({ nfts }) {
  return (
    <>
      <Head>
        <title>Profile | Radish Square</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <main>
          <section>
            {/*  eslint-disable-next-line @next/next/no-img-element */}
            <Image
              src={banner}
              className="w-full h-[360px] object-cover"
              alt="banner"
            />

            {/* Profile Card */}
            <div className="relative -mt-16 px-20 flex justify-between max-w-[1800px] mx-auto">
              <div>
                <div className="flex justify-start">
                  <div className="w-[112px] h-[112px] rounded-full border-4 border-white border-solid flex justify-center items-center">
                    <Image
                      src={banner}
                      className="rounded-full"
                      alt="profile"
                      width={108}
                      height={108}
                    />
                  </div>
                </div>

                <h2 className="font-extrabold text-[40px] mt-2">
                  Francisco Vann
                </h2>

                <div className="flex items-center gap-x-2 mt-3">
                  <div className="text-sm font-extrabold -mt-[2px]">
                    Wallet address:
                  </div>
                  <div>
                    {true ? (
                      <WalletNumber
                        style="text-sm text-primary font-semibold !m-0 !p-0"
                        walletNumber={
                          "8646374bhnbvshdfsvhfgsd8r7e7t3843578sdsds"
                        }
                      />
                    ) : (
                      <p className="text-sm text-[#94999D]">
                        No wallet connected
                      </p>
                    )}
                  </div>
                </div>

                <div className="max-w-[508px] text-[#94999D] mt-3">
                  Curated of beautiful and charming NFTs by Frans. Crafted where
                  even the most intricate. Let’s connect and share the best
                  thing!
                </div>

                <div className="flex items-center gap-x-8  my-6">
                  <div className="text-center">
                    <p className="font-extrabold text-xl">{15}</p>
                    <p className="mt-1 text-sm text-secondaryGray">followers</p>
                  </div>

                  <div className="text-center">
                    <p className="font-extrabold text-xl">100</p>
                    <p className="mt-1 text-sm text-secondaryGray">items</p>
                  </div>

                  <div className="text-center">
                    <p className="font-extrabold text-xl">{26}</p>
                    <p className="mt-1 text-sm text-secondaryGray">following</p>
                  </div>
                </div>

                <div className="flex items-center gap-x-2 mt-4">
                  {false ? (
                    <Button
                      className="w-[120px] h-[46px] rounded-[12px] font-bold"
                      type="primary"
                      onClick={() => {
                        router.push("/my-account/" + router.query.userId);
                      }}
                    >
                      Edit Profile
                    </Button>
                  ) : (
                    <Button
                      className="w-[120px] h-[46px] rounded-[12px] font-bold"
                      type="primary"
                    >
                      <div className="flex justify-center items-center gap-1.5">
                        <MdGroupAdd className="w-[20px] h-[20px]" />
                        {/* {followers.includes(session?.token?.sub)
                        ? "Following"
                        : "Follow"} */}
                        Follow
                      </div>
                    </Button>
                  )}

                  <Button
                    className="h-[46px] w-[46px] rounded-full flex justify-center items-center"
                    onClick={() => {
                      // copy to clipboard
                      navigator.clipboard.writeText(
                        `${process.env.NEXT_PUBLIC_BASE_URL}/profile/${router.query.userId}`
                      );
                      message.success("Link copied to clipboard");
                    }}
                  >
                    <MdOutlineShare className="" />
                  </Button>
                </div>
              </div>

              <div className="mt-28 ">
                <p className="font-extrabold text-sm">
                  Find us on social media
                </p>

                <div className="my-4 flex items-center gap-x-1">
                  {true && (
                    <Image
                      src={telegramLogo}
                      className="cursor-pointer"
                      width={18}
                      height={18}
                      alt="telegram"
                      onClick={() => {
                        window.open(user?.facebook, "_blank");
                      }}
                    />
                  )}
                  {true && (
                    <TwitterIcon
                      className="ml-3 cursor-pointer"
                      onClick={() => {
                        window.open(user?.twitter, "_blank");
                      }}
                    />
                  )}
                </div>
              </div>
            </div>
          </section>

          <section className="px-20 my-10 max-w-[1800px] mx-auto">
            <ProfileMain nfts={nfts} />
          </section>
        </main>
      </Container>
    </>
  );
}

export async function getServerSideProps(context) {
  // console.log(context.query.userId);
  // console.log("user profile");
  const response = await axios.post(
    `${process.env.API_BASE_URL}/api/nft/with-filters?page=1`,
    {
      filters: [],
      primaryFilters: {
        collectionIdentifier: "buff",
        // price not equal to null in mongoose
        price: { $ne: null },
      },
      sortBy: {
        price: -1,
      },
    }
  );

  // console.log(response.data);
  return {
    props: {
      nfts: response.data.nfts,
    },
  };
}
