import { Button, Input, message } from "antd";
import Head from "next/head";
import { useState } from "react";
import { signIn } from "next-auth/react";
import axios from "axios";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);

  return (
    <>
      <Head>
        <title>Radish Admin / Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen bg-secondaryGray bg-opacity-10 flex justify-center items-center">
        <section className="w-[500px] h-[500px] bg-secondaryLightDark rounded-2xl flex flex-col items-center justify-center">
          <div className="w-10 h-10 flex items-center justify-center text-white font-bold bg-primary rounded-full">
            Red.
          </div>
          <p className="text-[35px] font-extrabold mt-4 text-center">
            Radish Admin Login
          </p>

          <div className="px-6 w-[480px] mt-6">
            <div className="w-full">
              {/* <label htmlFor="email" className="block">
                Email
              </label> */}
              <Input
                id="email"
                type="email"
                name="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                size="large"
                placeholder="Enter your listed email"
                style={{
                  borderRadius: "24px",
                  fontWeight: "bold",
                }}
                className="w-full py-3 px-5 placeholder:text-neutral-300 mt-2"
              />
            </div>
            <div className="w-full">
              {/* <label htmlFor="email" className="block">
                Email
              </label> */}
              <Input
                id="password"
                type="password"
                name="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                size="large"
                placeholder="Enter password"
                style={{
                  borderRadius: "24px",
                  fontWeight: "bold",
                }}
                className="w-full py-3 px-5 placeholder:text-neutral-300 mt-2"
              />
            </div>
            <Button
              className="w-full rounded-[24px] h-[46px] font-bold mt-4"
              type="primary"
              onClick={async () => {
                setLoading(true);

                try {
                  // verify admin
                  const response = await axios.post(
                    `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/admin/auth/verify-admin`,
                    {
                      email,
                      password,
                    }
                  );

                  if (!response.data?.success) {
                    message.error("Invalid credentials");
                    setLoading(false);
                    return;
                  }

                  localStorage.setItem(
                    "RADSIH_ADMIN_AUTH_TOKEN",
                    response.data?.token
                  );

                  signIn("email", {
                    callbackUrl: "/",
                    email,
                  });
                } catch (error) {
                  message.error("Invalid credentials");
                  setLoading(false);
                  return;
                }
              }}
              loading={loading}
            >
              Authanticate
            </Button>
          </div>
        </section>
      </main>
    </>
  );
}
