import { Result } from "antd";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Radish Admin / Verify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Result
          status="success"
          title="Verification email sent!"
          subTitle={`We've sent a verification email. Click the link in the email to log in.`}
        />
      </main>
    </>
  );
}
