import Navbar from "@/components/Navbar";
import { InboxOutlined } from "@ant-design/icons";
import { Button, Upload, message } from "antd";
import { getSession } from "next-auth/react";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

export default function UploadNfts() {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleSubmit = (e) => {};

  //   console.log("file", file);

  return (
    <>
      <Head>
        <title>Radish Admin / Upload Nfts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <section className="mt-8">
          <h2 className="text-2xl font-bold text-center my-5">Upload Nfts</h2>
          <form onSubmit={handleSubmit} className=" max-w-xl mx-auto mt-10">
            <Upload.Dragger
              name="file"
              accept=".json"
              multiple={false}
              showUploadList={false}
              action={(file) => {
                setLoading(true);
                const fileReader = new FileReader();
                fileReader.readAsText(file, "UTF-8");
                fileReader.onload = (e) => {
                  setFile(e.target.result);
                  const token = localStorage.getItem("RADSIH_ADMIN_AUTH_TOKEN");
                  axios
                    .post(
                      `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/nft/upload-nfts`,
                      {
                        nfts: JSON.parse(e.target.result),
                      },
                      {
                        headers: {
                          "Content-Type": "application/json",
                          Authorization: `Bearer ${token}`,
                        },
                      }
                    )
                    .then((res) => {
                      //   console.log(res.data);
                      setLoading(false);
                      if (res.data.success) {
                        message.success("Nfts uploaded successfully");
                      }
                    });
                };
              }}
            >
              <p className="ant-upload-drag-icon">
                <InboxOutlined />
              </p>
              {loading ? (
                <p className="ant-upload-text !text-primary">
                  Uploading, please wait...
                </p>
              ) : (
                <p className="ant-upload-text">
                  Click or drag file to this area to upload
                </p>
              )}
            </Upload.Dragger>
          </form>
        </section>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}
