import { Tabs, Button } from "antd";
import Head from "next/head";
import axios from "axios";
import { MdKeyboardArrowLeft } from "react-icons/md";
import Image from "next/image";
import { useRouter } from "next/router";
import Container from "@/components/layouts/Container";
import CollectionList from "@/components/explore/CollectionList";

function filterByCategory(collections, type) {
  return collections.filter((collection) => {
    return collection.type === type;
  });
}

export default function Explore({ collections }) {
  const router = useRouter();
  console.log(collections);

  const tabItems = [
    {
      key: "1",
      label: <span className="font-bold">All</span>,
      children: (
        <div>
          <CollectionList data={collections} />
        </div>
      ),
    },
    {
      key: "2",
      label: <span className="font-bold">Trending</span>,
      children: (
        <div>
          <CollectionList data={collections} />
        </div>
      ),
    },
    {
      key: "3",
      label: <span className="font-bold">Collectibles</span>,
      children: (
        <div>
          <CollectionList
            data={filterByCategory(collections, "collectibles")}
          />
        </div>
      ),
    },
    {
      key: "4",
      label: <span className="font-bold">Art</span>,
      children: (
        <div>
          <CollectionList data={filterByCategory(collections, "art")} />
        </div>
      ),
    },
    {
      key: "5",
      label: <span className="font-bold">Music</span>,
      children: (
        <div>
          <CollectionList data={filterByCategory(collections, "music")} />
        </div>
      ),
    },
    {
      key: "6",
      label: <span className="font-bold">Photography</span>,
      children: (
        <div>
          <CollectionList data={filterByCategory(collections, "photography")} />
        </div>
      ),
    },
  ];
  return (
    <>
      <Head>
        <title>Explore | Radish Square</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <main className="max-w-[1300px] mx-auto px-4 mt-10 mb-28 min-h-[55vh]">
          <h2 className="text-[24px] sm:text-[40px] font-extrabold  my-6 text-center">
            Explore NFTs
          </h2>
          <Tabs items={tabItems} centered className="" />
        </main>
      </Container>
    </>
  );
}

// fetch data from api
export async function getServerSideProps() {
  const response = await axios.get(
    `${process.env.API_BASE_URL}/api/collection`
  );

  // console.log(response.data);
  return {
    props: {
      collections: response?.data?.collections || [],
    },
  };
}
