import Head from "next/head";
import Navbar from "@/components/common/Navbar";
import HeroSlider from "@/components/home/HeroSlider";
import SingleMoreNft from "@/components/nft/SingleMoreNft";
import { useState } from "react";
import Art from "../images/Art.png";
import Shape from "../images/Diamond_Shape.png";
import Image from "next/image";
import TrendingCollection from "@/components/home/TrendingCollection";
import TrendingToday from "@/components/home/TrendingToday";
import TrendingCreators from "@/components/home/TopSellingCreators";
import LiveAuctions from "@/components/home/LiveAuctions";
import CategorySlider from "@/components/home/CategotySlider";
import EditorsPick from "@/components/home/EditorsPick";
import axios from "axios";
import { Empty } from "antd";

// dummy data
import { getCollections, getNfts } from "@/lib/dummy";
import Footer from "@/components/common/Footer";
const collections = getCollections(6);
const editorPickNfts = getNfts(6);

export default function Home({}) {
  const [trendingCollectionSpan, setTrendingCollectionSpan] = useState(1);

  return (
    <>
      <Head>
        <title>Radish Square: The Friendliest Platform in the World!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <HeroSlider collections={collections} />

        <section className="max-w-[1440px] mx-auto xl:px-[84px] lg:px-[48px] md:px-[36px] px-[24px] mt-8">
          <p className="font-extrabold text-[24px] mb-8 text-center sm:text-start">
            Editor’s Pick ✨
          </p>
          <div className="mt-4 "></div>
        </section>

        <section className="mt-20 my-8 max-w-[1440px] mx-auto xl:px-[84px] lg:px-[48px] md:px-[36px] px-[24px]">
          <div className="flex justify-start items-start gap-4 flex-col sm:flex-row sm:justify-between sm:items-center">
            <p className="font-extrabold text-[24px] self-center sm:self-start">
              Trending Collections 🔥
            </p>
            <div className="flex items-center gap-x-2 self-center sm:self-start">
              <div
                className={`w-[94px] h-[36px] rounded-[18px] flex items-center justify-center font-extrabold text-xs cursor-pointer ${
                  trendingCollectionSpan === 1
                    ? "bg-rose-100 text-primary dark:text-white dark:bg-primary"
                    : "border border-solid border-[#CFDBD599]"
                }`}
                onClick={() => {
                  setTrendingCollectionSpan(1);
                }}
              >
                1 Day
              </div>
              <div
                className={`w-[94px] h-[36px] rounded-[18px] flex items-center justify-center font-extrabold text-xs cursor-pointer ${
                  trendingCollectionSpan === 7
                    ? "bg-rose-100 text-primary dark:text-white dark:bg-primary"
                    : "border border-solid border-[#CFDBD599]"
                }`}
                onClick={() => {
                  setTrendingCollectionSpan(7);
                }}
              >
                7 Days
              </div>
              <div
                className={`w-[94px] h-[36px] rounded-[18px] flex items-center justify-center font-extrabold text-xs cursor-pointer ${
                  trendingCollectionSpan === 30
                    ? "bg-rose-100 text-primary dark:text-white dark:bg-primary"
                    : "border border-solid border-[#CFDBD599]"
                }`}
                onClick={() => {
                  setTrendingCollectionSpan(30);
                }}
              >
                30 Days
              </div>
            </div>
          </div>
          {/* trending collections detail  */}
          <div className="flex flex-col md:flex-row xl:gap-6 lg:gap-4 mt-3">
            <div className="md:w-1/2 w-full hidden sm:block">
              <table class="w-full table-auto">
                <thead>
                  <tr>
                    <th className="font-bold uppercase text-xs text-start py-4 ">
                      Collections
                    </th>
                    <th className="font-bold uppercase text-xs text-end py-4">
                      Floor Price
                    </th>
                    <th className="font-bold uppercase text-xs text-end py-4">
                      Volume
                    </th>
                  </tr>
                </thead>
              </table>
            </div>
            <div className="md:w-1/2 w-full hidden md:block">
              <table class="w-full table-auto">
                <thead className="">
                  <tr>
                    <th className="font-bold uppercase text-xs text-start py-4">
                      Collections
                    </th>
                    <th className="font-bold uppercase text-xs text-end py-4">
                      Floor Price
                    </th>
                    <th className="font-bold uppercase text-xs text-end py-4">
                      Volume
                    </th>
                  </tr>
                </thead>
              </table>
            </div>

            {/* mobile version  */}
            <div className="w-full sm:hidden block ">
              <table class="w-full table-auto"></table>
            </div>
          </div>
          <div className="text-center text-secondaryDarkGray my-6">
            {/* Not enough data to show trending collections */}
            <Empty
              description="Not enough data to show trending collections"
              image={Empty.PRESENTED_IMAGE_SIMPLE}
            />
          </div>
        </section>

        {/* top sellings creators today  */}
        <section className="my-20 max-w-[1440px] mx-auto xl:px-[84px] lg:px-[48px] md:px-[36px] px-[24px]">
          <div className="w-full flex justify-center items-center sm:justify-start flex-row">
            <p className="font-extrabold text-[24px] ">Top Collectors ✒️</p>
          </div>
          <div className="w-full my-8"></div>
        </section>

        <Footer />
      </div>
    </>
  );
}
