import Layout from "@/components/utils/Layout";
import Head from "next/head";
import axios from "axios";
import ListNftExplore from "@/components/explore/ListNftExplore";
import SingleCollectionNft from "@/components/collection/SingleCollectionNft";
import { useRouter } from "next/router";

export default function Search({ collections, nfts }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Search | Radish Square</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="max-w-[1280px] mx-auto min-h-[70vh] mb-24 p-4">
          <h2 className="font-extrabold text-[32px] my-10 text-center">
            Showing search result for “{router.query.query}”
          </h2>
          {collections.length === 0 && nfts.length === 0 && (
            <div className="min-h-[40vh] flex items-center justify-center">
              <p className=" text-secondaryDarkGray">No data found</p>
            </div>
          )}
          {collections.length > 0 && (
            <>
              <p className="text-secondaryGray font-bold my-3">
                Collection results
              </p>
              <ListNftExplore data={collections} />
            </>
          )}
          {nfts.length > 0 && (
            <div className="my-10 p-2">
              <p className="text-secondaryGray font-bold my-3">
                Showing {nfts.length} NFTs
              </p>
              <div className="grid xl:grid-cols-4 lg:grid-cols-3 gap-y-5 md:gap-x-4 grid-cols-1 md:grid-cols-2 ">
                {nfts.map((nft) => {
                  return <SingleCollectionNft key={nft._id} nft={nft} />;
                })}
              </div>
            </div>
          )}
        </main>
      </Layout>
    </>
  );
}

// fetch data from api-server
export async function getServerSideProps(context) {
  const { query } = context.query;

  // make sure query is not empty or deosn't contain only spaces or / or \ or ?  or % or & or * or ( or ) or + or , or : or ; or = or @ or [ or ]
  if (
    !query ||
    query.trim() === "" ||
    query.includes("/") ||
    query.includes("\\") ||
    query.includes("?") ||
    query.includes("%") ||
    query.includes("&") ||
    query.includes("*") ||
    query.includes("(") ||
    query.includes(")") ||
    query.includes("+") ||
    query.includes(",") ||
    query.includes(":") ||
    query.includes(";") ||
    query.includes("=") ||
    query.includes("@") ||
    query.includes("[") ||
    query.includes("]")
  ) {
    return {
      props: {
        collections: [],
        nfts: [],
      },
    };
  }

  if (query.startsWith("rdx") || query.endsWith(".xrd")) {
    const response = await axios.get(
      `${process.env.API_BASE_URL}/api/user/search-user/${query}`
    );

    if (response.data?.user) {
      return {
        redirect: {
          destination: `/profile/${response.data.user._id}`,
          permanent: false,
        },
      };
    }
  }

  //   console.log("query", query);
  const response = await axios.get(
    `${process.env.API_BASE_URL}/api/collection/search/${query}`
  );

  //   console.log(response.data);

  return {
    props: {
      collections: response.data?.collections || [],
      nfts: response.data?.nfts || [],
    },
  };
}
